vim.keymap.set("n", "<leader>ex", vim.cmd.Ex)
vim.keymap.set("n", "<leader>y", "\"+y")
vim.keymap.set("n", "<leader>y", "\"+Y")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("v", "<leader>x", "\"+x")
vim.keymap.set("n", "<leader>p", "\"+p")
vim.keymap.set("n", "<leader>d", vim.diagnostic.open_float)
